"""Shared helpers for build_semantic_map.py (offline) and semantic_goal.py (online).

Not an entry point -- installed alongside those two scripts (see CMakeLists.txt) so
`import semantic_map_common` resolves via Python's own auto-added script directory.

Frame-convention note (the one non-obvious piece of math in this whole package): this
repo's `camera_face` TF frame is a zero-rotation child of `base_link` -- it follows
robot convention (+X forward, +Z up), NOT the standard camera optical convention
(+X right, +Y down, +Z forward). There is no separate `camera_face_optical_frame` in
this repo's TF tree. But depth images are generated by gz-sim's rgbd_camera sensor
using the standard pinhole/optical convention internally regardless of the TF frame's
own rotation -- so `pixel_to_optical_xyz()` below yields a point in optical
convention, which `optical_to_face()` then rotates into `camera_face`'s own axes
*before* any TF lookup is applied. Skipping this rotation silently swaps/flips axes
(x_opt=right != x_face=forward) without erroring -- the failure mode is a voxel map
that looks coherent but is systematically misaligned with reality.
"""
import math

import numpy as np
import rclpy
from geometry_msgs.msg import TransformStamped
from rclpy.duration import Duration
from rclpy.time import Time
from tf2_ros import Buffer


class CameraModel:
    """Pinhole intrinsics from a sensor_msgs/CameraInfo (or its rosbags-decoded twin)."""

    def __init__(self, fx: float, fy: float, cx: float, cy: float):
        self.fx, self.fy, self.cx, self.cy = fx, fy, cx, cy

    @classmethod
    def from_camera_info(cls, raw_camera_info) -> 'CameraModel':
        k = raw_camera_info.k  # row-major 3x3: [fx, 0, cx, 0, fy, cy, 0, 0, 1]
        return cls(fx=float(k[0]), fy=float(k[4]), cx=float(k[2]), cy=float(k[5]))

    def pixel_to_optical_xyz(self, us, vs, depths) -> np.ndarray:
        """Vectorized pixel(s) + depth -> point(s) in optical convention (...,3).

        us/vs/depths may be scalars or same-shaped arrays (e.g. every pixel in a
        mask). Standard pinhole back-projection: X=(u-cx)*Z/fx, Y=(v-cy)*Z/fy, Z=depth.
        """
        us = np.asarray(us, dtype=np.float64)
        vs = np.asarray(vs, dtype=np.float64)
        depths = np.asarray(depths, dtype=np.float64)
        x = (us - self.cx) * depths / self.fx
        y = (vs - self.cy) * depths / self.fy
        return np.stack([x, y, depths], axis=-1)


def optical_to_face(p_opt: np.ndarray) -> np.ndarray:
    """Rotate point(s) (...,3) from optical convention into camera_face's robot
    convention. See module docstring. optical +Z (forward) -> face +X (forward);
    optical +X (right) -> face -Y (since face +Y is left); optical +Y (down) ->
    face -Z (since face +Z is up)."""
    x_opt, y_opt, z_opt = p_opt[..., 0], p_opt[..., 1], p_opt[..., 2]
    return np.stack([z_opt, -x_opt, -y_opt], axis=-1)


def _to_transform_stamped(raw) -> TransformStamped:
    """Copy a rosbags-decoded TransformStamped's fields into a real
    geometry_msgs.msg.TransformStamped -- tf2_ros.Buffer.set_transform() needs the
    real ROS message type, not rosbags' own structurally-similar-but-distinct class.
    """
    msg = TransformStamped()
    msg.header.stamp.sec = int(raw.header.stamp.sec)
    msg.header.stamp.nanosec = int(raw.header.stamp.nanosec)
    msg.header.frame_id = raw.header.frame_id
    msg.child_frame_id = raw.child_frame_id
    msg.transform.translation.x = float(raw.transform.translation.x)
    msg.transform.translation.y = float(raw.transform.translation.y)
    msg.transform.translation.z = float(raw.transform.translation.z)
    msg.transform.rotation.x = float(raw.transform.rotation.x)
    msg.transform.rotation.y = float(raw.transform.rotation.y)
    msg.transform.rotation.z = float(raw.transform.rotation.z)
    msg.transform.rotation.w = float(raw.transform.rotation.w)
    return msg


class TfBagBuffer:
    """A tf2_ros.Buffer fed directly from decoded bag TFMessages, not a live topic.

    tf2_ros.Buffer works standalone -- no rclpy.init()/node/subscription needed -- as
    long as nothing tries to use TransformListener (which does need a live node to
    subscribe /tf, /tf_static). Feeding it directly via set_transform()/
    set_transform_static() gives the same SLERP time-interpolated lookups a live
    TransformListener would, entirely offline. Default cache_time is much larger
    than tf2's usual ~10s default -- a whole bag's worth of transforms needs to stay
    queryable, not just the last few seconds.
    """

    def __init__(self, cache_time_s: float = 3600.0):
        self.buffer = Buffer(cache_time=Duration(seconds=cache_time_s))

    def add_tf_message(self, raw_tf_message, static: bool = False):
        for raw_transform in raw_tf_message.transforms:
            ts = _to_transform_stamped(raw_transform)
            if static:
                self.buffer.set_transform_static(ts, 'bag')
            else:
                self.buffer.set_transform(ts, 'bag')

    def lookup(self, target_frame: str, source_frame: str, stamp_sec: int, stamp_nanosec: int):
        stamp = Time(seconds=stamp_sec, nanoseconds=stamp_nanosec)
        return self.buffer.lookup_transform(target_frame, source_frame, stamp)


class VoxelGrid:
    """Streaming weighted-average voxel accumulator.

    add_point() can be called in any order, any number of times per voxel (e.g. from
    overlapping masks across many frames); finalize() reduces the running sums into
    one L2-normalized embedding per voxel (so query-time cosine similarity is a plain
    dot product) and drops the running-sum state.
    """

    def __init__(self, voxel_size_m: float, eps: float = 1e-3):
        self.voxel_size = voxel_size_m
        self.eps = eps
        self._acc = {}  # (i, j, k) -> [weight_sum: float, embed_weighted_sum: np.ndarray]
        self.voxel_indices = None
        self.voxel_centers = None
        self.embeddings = None
        self.weights = None

    def _index(self, xyz: np.ndarray):
        return tuple(np.floor(np.asarray(xyz) / self.voxel_size).astype(np.int64).tolist())

    def _center(self, idx) -> np.ndarray:
        return (np.array(idx, dtype=np.float64) + 0.5) * self.voxel_size

    def __len__(self):
        return len(self._acc)

    def add_point(self, xyz: np.ndarray, embedding: np.ndarray, base_weight: float = 1.0):
        idx = self._index(xyz)
        dist = float(np.linalg.norm(np.asarray(xyz) - self._center(idx)))
        w = base_weight / max(self.eps, dist)
        entry = self._acc.get(idx)
        if entry is None:
            self._acc[idx] = [w, w * embedding.astype(np.float64)]
        else:
            entry[0] += w
            entry[1] += w * embedding.astype(np.float64)

    def finalize(self) -> 'VoxelGrid':
        n = len(self._acc)
        if n == 0:
            self.voxel_indices = np.zeros((0, 3), dtype=np.int32)
            self.voxel_centers = np.zeros((0, 3), dtype=np.float32)
            self.embeddings = np.zeros((0, 0), dtype=np.float32)
            self.weights = np.zeros((0,), dtype=np.float32)
            return self

        embed_dim = next(iter(self._acc.values()))[1].shape[0]
        indices = np.empty((n, 3), dtype=np.int32)
        centers = np.empty((n, 3), dtype=np.float32)
        embeddings = np.empty((n, embed_dim), dtype=np.float32)
        weights = np.empty((n,), dtype=np.float32)
        for i, (idx, (w, embed_sum)) in enumerate(self._acc.items()):
            indices[i] = idx
            centers[i] = self._center(idx)
            avg = embed_sum / w
            norm = np.linalg.norm(avg)
            embeddings[i] = (avg / norm) if norm > 0 else avg
            weights[i] = w
        self.voxel_indices, self.voxel_centers = indices, centers
        self.embeddings, self.weights = embeddings, weights
        return self

    def save(self, path: str):
        np.savez(
            path,
            voxel_centers=self.voxel_centers,
            voxel_indices=self.voxel_indices,
            embeddings=self.embeddings,
            weights=self.weights,
            voxel_size_m=np.float32(self.voxel_size),
        )

    @staticmethod
    def load(path: str) -> 'VoxelGrid':
        data = np.load(path)
        vg = VoxelGrid(voxel_size_m=float(data['voxel_size_m']))
        vg.voxel_centers = data['voxel_centers']
        vg.voxel_indices = data['voxel_indices']
        vg.embeddings = data['embeddings']
        vg.weights = data['weights']
        return vg


def quat_to_matrix(x: float, y: float, z: float, w: float) -> np.ndarray:
    """Standard unit-quaternion -> 3x3 rotation matrix."""
    n = x * x + y * y + z * z + w * w
    if n < 1e-12:
        return np.eye(3)
    s = 2.0 / n
    xs, ys, zs = x * s, y * s, z * s
    wx, wy, wz = w * xs, w * ys, w * zs
    xx, xy, xz = x * xs, x * ys, x * zs
    yy, yz, zz = y * ys, y * zs, z * zs
    return np.array([
        [1 - (yy + zz), xy - wz, xz + wy],
        [xy + wz, 1 - (xx + zz), yz - wx],
        [xz - wy, yz + wx, 1 - (xx + yy)],
    ])


def transform_points(transform_stamped, points: np.ndarray) -> np.ndarray:
    """Apply a geometry_msgs/TransformStamped to point(s) (...,3) -> (...,3)."""
    t = transform_stamped.transform.translation
    r = transform_stamped.transform.rotation
    rot = quat_to_matrix(r.x, r.y, r.z, r.w)
    translation = np.array([t.x, t.y, t.z])
    return points @ rot.T + translation


def expand_bbox(box, pad_px: int, shape):
    """box: (x1, y1, x2, y2) pixels. shape: (height, width, ...). Clamps to image bounds."""
    x1, y1, x2, y2 = box
    h, w = shape[0], shape[1]
    return (
        max(0, int(x1) - pad_px),
        max(0, int(y1) - pad_px),
        min(w, int(x2) + pad_px),
        min(h, int(y2) + pad_px),
    )


def encode_query(model_name: str, pretrained: str, query: str, device: str) -> np.ndarray:
    """Text -> L2-normalized CLIP embedding, via the text tower. model_name/pretrained
    must match whatever build_semantic_map.py used (checked against a map's sibling
    .meta.json by callers) -- embeddings from mismatched checkpoints aren't comparable.
    """
    import open_clip
    import torch
    model, _, _ = open_clip.create_model_and_transforms(model_name, pretrained=pretrained)
    tokenizer = open_clip.get_tokenizer(model_name)
    model = model.to(device).eval()
    tokens = tokenizer([query]).to(device)
    with torch.no_grad():
        feat = model.encode_text(tokens)
        feat = feat / feat.norm(dim=-1, keepdim=True)
    return feat.squeeze(0).cpu().numpy().astype(np.float32)


def cosine_topk(embeddings: np.ndarray, query: np.ndarray, k: int):
    """embeddings: (N,D) L2-normalized. query: (D,) L2-normalized.

    Returns (indices, similarities), both length min(k, N), sorted descending.
    """
    sims = embeddings @ query
    k = min(k, len(sims))
    if k == 0:
        return np.empty((0,), dtype=np.int64), np.empty((0,), dtype=np.float32)
    idx = np.argpartition(-sims, k - 1)[:k]
    idx = idx[np.argsort(-sims[idx])]
    return idx, sims[idx]


def send_navigate_to_pose_goal(node, x: float, y: float, yaw: float, timeout_s: float = 120.0) -> bool:
    """Blocking rclpy ActionClient send, same pattern as send_nav_goal.py (duplicated,
    not imported -- these are CMake-installed scripts in different packages, not an
    importable Python package). `node` must be spin-able (spin_until_future_complete
    is used against it) -- pass the rclpy.Node this is called from.
    """
    from geometry_msgs.msg import PoseStamped
    from nav2_msgs.action import NavigateToPose
    from rclpy.action import ActionClient

    client = ActionClient(node, NavigateToPose, 'navigate_to_pose')
    node.get_logger().info('Waiting for navigate_to_pose action server...')
    if not client.wait_for_server(timeout_sec=15.0):
        node.get_logger().error('Action server not available -- is nav_stack.launch.py up?')
        return False

    goal = NavigateToPose.Goal()
    goal.pose = PoseStamped()
    goal.pose.header.frame_id = 'map'
    goal.pose.header.stamp = node.get_clock().now().to_msg()
    goal.pose.pose.position.x = x
    goal.pose.pose.position.y = y
    goal.pose.pose.orientation.z = math.sin(yaw / 2.0)
    goal.pose.pose.orientation.w = math.cos(yaw / 2.0)

    node.get_logger().info(f'Sending goal: x={x:.2f} y={y:.2f} yaw={yaw:.2f}')
    send_future = client.send_goal_async(goal)
    rclpy.spin_until_future_complete(node, send_future, timeout_sec=15.0)
    goal_handle = send_future.result()
    if goal_handle is None or not goal_handle.accepted:
        node.get_logger().error('Goal rejected or send timed out')
        return False

    result_future = goal_handle.get_result_async()
    rclpy.spin_until_future_complete(node, result_future, timeout_sec=timeout_s)
    result = result_future.result()
    if result is None:
        node.get_logger().error(f'Timed out waiting for result after {timeout_s}s')
        return False
    node.get_logger().info(f'Result status: {result.status}')
    return result.status == 4  # nav2_msgs GoalStatus.STATUS_SUCCEEDED
